blank_issues_enabled: false
contact_links:
  - name: Appeal other bans
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    about: If you were banned for any other reason, please appeal over at https://appeal.bans.gg/form?id=Aliucord
